### ISSUE TITLE
history hard to read

### ISSUE THREAD

**Issue by illwieckz** [iosof2mp/iosof2mp#1]
Hi, by the name of the project this looks very interesting ! But why importing the source tree without history instead of cloning the upstream repository to enable easy merge/pull/rebase/cherry-picks ? This closes the door to cooperation from the start and then introduces a risk for the viability of your project. This also deletes the contribution authorship git naturally takes care of.

**Comment by AJSchat** [comment]
Hi there.

Thanks for your concern, but after giving it some thought I have to disagree. While true that merging and pulling from upstream is a lot harder this way it does make _this_ project history a lot easier to follow and read. That's why I opted for this git workflow. Merges, or a PR upstream, will be done periodically by myself so if anything I'm only making it harder for myself.

Authorship should not be an issue in the future as well as all participating parties (either directly or indirectly) will receive proper credits in both repository README, license blocks at the beginning of each file and, if applicable, on individual commits.

It's very hard to pin this project history on a single project as it will undoubtedly share lots of code with both ioquake3, OpenJK, Jedi Academy/Jedi Outcast source dumps, rd-rend2 and more.

Thanks again, if you have more concerns be sure to let me know.
